@baseUrl=http://localhost:9000
###
GET {{baseUrl}}/v1/user/gethome
###
GET {{baseUrl}}/v1/user/gethome2
###
GET {{baseUrl}}/v1/user/getemail

###
GET {{baseUrl}}/v1/blockchain/gethome
###
GET {{baseUrl}}/v1/blockchain/gethome2

###
GET {{baseUrl}}/v1/blockchain/getemail
###
GET {{baseUrl}}/v1/blockchain/greet/SripalJainFromSingapore

###
GET {{baseUrl}}/v1/blockchain/get/counter/count

###
GET {{baseUrl}}/v1/blockchain/getmessage
###
GET {{baseUrl}}/v1/blockchain/counter/increment